const actionTypes = {
	ALL_CARS: 'ALL_CARS',
	SINGLE_CAR: 'SINGLE_CAR',
  ADD_CAR: 'ADD_CAR',
  REMOVE_CAR: 'REMOVE_CAR',
	SIGN_UP: 'SIGN_UP',
	USER_SIGNUP: 'USER_SIGNUP',
	USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
	USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
	AUTHENTICATE: 'AUTHENTICATE',
	USER_LOGIN: 'USER_LOGIN',
	USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
};

export default actionTypes;
